SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- --------------------------------------------------------

--
-- Table structure for table `countries_all`
--

CREATE TABLE `countries_all` (
  `id` int(11) NOT NULL,
  `name` varchar(45) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Basic',
  `capitals` varchar(34) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `alpha_2_code` varchar(3) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'ISO 3166-1 alpha-2',
  `alpha_3_code` varchar(4) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'ISO 3166-1 alpha-3',
  `numeric_code` varchar(4) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'ISO 3166-1 Numeric Code'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `countries_all`
--

INSERT INTO `countries_all` (`id`, `name`, `capitals`, `alpha_2_code`, `alpha_3_code`, `numeric_code`) VALUES
(1, 'Algeria', 'Algiers', 'DZ', 'DZA', '012'),
(2, 'Egypt', 'Cairo', 'EG', 'EGY', '818'),
(3, 'Libya', 'Tripoli', 'LY', 'LBY', '434'),
(4, 'Morocco', 'Rabat', 'MA', 'MAR', '504'),
(5, 'Sudan', 'Khartoum', 'SD', 'SDN', '729'),
(6, 'Tunisia', 'Tunis', 'TN', 'TUN', '788'),
(7, 'Western Sahara', 'El Aaiún', 'EH', 'ESH', '732'),
(8, 'British Indian Ocean Territory', 'Camp Justice', 'IO', 'IOT', '086'),
(9, 'Burundi', 'Bujumbura', 'BI', 'BDI', '108'),
(10, 'Comoros', 'Moroni', 'KM', 'COM', '174'),
(11, 'Djibouti', 'Djibouti', 'DJ', 'DJI', '262'),
(12, 'Eritrea', 'Asmara', 'ER', 'ERI', '232'),
(13, 'Ethiopia', 'Addis Ababa', 'ET', 'ETH', '231'),
(14, 'French Southern Territories', 'Saint-Pierre', 'TF', 'ATF', '260'),
(15, 'Kenya', 'Nairobi', 'KE', 'KEN', '404'),
(16, 'Madagascar', 'Antananarivo', 'MG', 'MDG', '450'),
(17, 'Malawi', 'Lilongwe', 'MW', 'MWI', '454'),
(18, 'Mauritius', 'Port Louis', 'MU', 'MUS', '480'),
(19, 'Mayotte', '-', 'YT', 'MYT', '175'),
(20, 'Mozambique', 'Maputo', 'MZ', 'MOZ', '508'),
(21, 'Réunion', '-', 'RE', 'REU', '638'),
(22, 'Rwanda', 'Kigali', 'RW', 'RWA', '646'),
(23, 'Seychelles', 'Victoria', 'SC', 'SYC', '690'),
(24, 'Somalia', 'Mogadishu', 'SO', 'SOM', '706'),
(25, 'South Sudan', 'Juba', 'SS', 'SSD', '728'),
(26, 'Tanzania', 'Dodoma', 'TZ', 'TZA', '834'),
(27, 'Uganda', 'Kampala', 'UG', 'UGA', '800'),
(28, 'Zambia', 'Lusaka', 'ZM', 'ZMB', '894'),
(29, 'Zimbabwe', 'Harare', 'ZW', 'ZWE', '716'),
(30, 'Angola', 'Luanda', 'AO', 'AGO', '024'),
(31, 'Cameroon', 'Yaounde', 'CM', 'CMR', '120'),
(32, 'Central African Republic', 'Bangui', 'CF', 'CAF', '140'),
(33, 'Chad', 'N\'Djamena', 'TD', 'TCD', '148'),
(34, 'Congo', 'Brazzaville', 'CG', 'COG', '178'),
(35, 'Congo', 'Kinshasa', 'CD', 'COD', '180'),
(36, 'Equatorial Guinea', 'Malabo', 'GQ', 'GNQ', '226'),
(37, 'Gabon', 'Libreville', 'GA', 'GAB', '266'),
(38, 'Sao Tome and Principe', 'São Tomé', 'ST', 'STP', '678'),
(39, 'Botswana', 'Gaborone', 'BW', 'BWA', '072'),
(40, 'Eswatini', 'Mbabane', 'SZ', 'SWZ', '748'),
(41, 'Lesotho', 'Maseru', 'LS', 'LSO', '426'),
(42, 'Namibia', 'Windhoek', 'NA', 'NAM', '516'),
(43, 'South Africa', 'Pretoria, Cape Town, Bloemfontein', 'ZA', 'ZAF', '710'),
(44, 'Benin', 'Porto-Novo', 'BJ', 'BEN', '204'),
(45, 'Burkina Faso', 'Ouagadougou', 'BF', 'BFA', '854'),
(46, 'Cabo Verde', 'Praia', 'CV', 'CPV', '132'),
(47, 'Côte d\'Ivoire', 'Yamoussoukro', 'CI', 'CIV', '384'),
(48, 'Gambia', 'Banjul', 'GM', 'GMB', '270'),
(49, 'Ghana', 'Accra', 'GH', 'GHA', '288'),
(50, 'Guinea', 'Conakry', 'GN', 'GIN', '324'),
(51, 'Guinea-Bissau', 'Bissau', 'GW', 'GNB', '624'),
(52, 'Liberia', 'Monrovia', 'LR', 'LBR', '430'),
(53, 'Mali', 'Bamako', 'ML', 'MLI', '466'),
(54, 'Mauritania', 'Nouakchott', 'MR', 'MRT', '478'),
(55, 'Niger', 'Niamey', 'NE', 'NER', '562'),
(56, 'Nigeria', 'Abuja', 'NG', 'NGA', '566'),
(57, 'Saint Helena, Ascension and Tristan da Cunha', 'Jamestown', 'SH', 'SHN', '654'),
(58, 'Senegal', 'Dakar', 'SN', 'SEN', '686'),
(59, 'Sierra Leone', 'Freetown', 'SL', 'SLE', '694'),
(60, 'Togo', 'Lomé', 'TG', 'TGO', '768'),
(61, 'Anguilla', 'The Valley', 'AI', 'AIA', '660'),
(62, 'Antigua and Barbuda', 'St. John\'s', 'AG', 'ATG', '028'),
(63, 'Aruba', 'Oranjestad', 'AW', 'ABW', '533'),
(64, 'Bahamas', 'Nassau', 'BS', 'BHS', '044'),
(65, 'Barbados', 'Bridgetown', 'BB', 'BRB', '052'),
(66, 'Bonaire, Sint Eustatius and Saba', '-', 'BQ', 'BES', '535'),
(67, 'Cayman Islands', 'George Town', 'KY', 'CYM', '136'),
(68, 'Cuba', 'Havana', 'CU', 'CUB', '192'),
(69, 'Curaçao', 'Willemstad', 'CW', 'CUW', '531'),
(70, 'Dominica', 'Roseau', 'DM', 'DMA', '212'),
(71, 'Dominican Republic', 'Santo Domingo', 'DO', 'DOM', '214'),
(72, 'Grenada', 'St. George\'s', 'GD', 'GRD', '308'),
(73, 'Guadeloupe', '-', 'GP', 'GLP', '312'),
(74, 'Haiti', 'Port-au-Prince', 'HT', 'HTI', '332'),
(75, 'Jamaica', 'Kingston', 'JM', 'JAM', '388'),
(76, 'Martinique', '-', 'MQ', 'MTQ', '474'),
(77, 'Montserrat', 'Plymouth, Brades Estate', 'MS', 'MSR', '500'),
(78, 'Puerto Rico', 'San Juan', 'PR', 'PRI', '630'),
(79, 'Saint Barthélemy', 'Gustavia', 'BL', 'BLM', '652'),
(80, 'Saint Kitts and Nevis', 'Basseterre', 'KN', 'KNA', '659'),
(81, 'Saint Lucia', 'Castries', 'LC', 'LCA', '662'),
(82, 'Saint Martin', 'Marigot', 'MF', 'MAF', '663'),
(83, 'Saint Vincent and the Grenadines', 'Kingstown', 'VC', 'VCT', '670'),
(84, 'Sint Maarten', 'Philipsburg', 'SX', 'SXM', '534'),
(85, 'Trinidad and Tobago', 'Port of Spain', 'TT', 'TTO', '780'),
(86, 'Turks and Caicos Islands', 'Cockburn Town', 'TC', 'TCA', '796'),
(87, 'Virgin Islands (British)', 'Road Town', 'VG', 'VGB', '092'),
(88, 'Virgin Islands (U.S.)', 'Charlotte Amalie', 'VI', 'VIR', '850'),
(89, 'Belize', 'Belmopan', 'BZ', 'BLZ', '084'),
(90, 'Costa Rica', 'San José', 'CR', 'CRI', '188'),
(91, 'El Salvador', 'San Salvador', 'SV', 'SLV', '222'),
(92, 'Guatemala', 'Guatemala City', 'GT', 'GTM', '320'),
(93, 'Honduras', 'Tegucigalpa', 'HN', 'HND', '340'),
(94, 'Mexico', 'Mexico City', 'MX', 'MEX', '484'),
(95, 'Nicaragua', 'Managua', 'NI', 'NIC', '558'),
(96, 'Panama', 'Panama City', 'PA', 'PAN', '591'),
(97, 'Bermuda', 'Hamilton', 'BM', 'BMU', '060'),
(98, 'Canada', 'Ottawa', 'CA', 'CAN', '124'),
(99, 'Greenland', 'Nuuk', 'GL', 'GRL', '304'),
(100, 'Saint Pierre and Miquelon', 'St. Pierre', 'PM', 'SPM', '666'),
(101, 'United States of America', 'Washington, D.C.', 'US', 'USA', '840'),
(102, 'Argentina', 'Buenos Aires', 'AR', 'ARG', '032'),
(103, 'Bolivia', 'Sucre, La Paz', 'BO', 'BOL', '068'),
(104, 'Bouvet Island', '-', 'BV', 'BVT', '074'),
(105, 'Brazil', 'Brasília', 'BR', 'BRA', '076'),
(106, 'Chile', 'Santiago', 'CL', 'CHL', '152'),
(107, 'Colombia', 'Bogotá', 'CO', 'COL', '170'),
(108, 'Ecuador', 'Quito', 'EC', 'ECU', '218'),
(109, 'Falkland Islands', 'Stanley', 'FK', 'FLK', '238'),
(110, 'French Guiana', '-', 'GF', 'GUF', '254'),
(111, 'Guyana', 'Georgetown', 'GY', 'GUY', '328'),
(112, 'Paraguay', 'Asunción', 'PY', 'PRY', '600'),
(113, 'Peru', 'Lima', 'PE', 'PER', '604'),
(114, 'South Georgia and the South Sandwich Islands', 'King Edward Point', 'GS', 'SGS', '239'),
(115, 'Suriname', 'Paramaribo', 'SR', 'SUR', '740'),
(116, 'Uruguay', 'Montevideo', 'UY', 'URY', '858'),
(117, 'Venezuela', 'Caracas', 'VE', 'VEN', '862'),
(118, 'Antarctica', '-', 'AQ', 'ATA', '010'),
(119, 'Kazakhstan', 'Astana', 'KZ', 'KAZ', '398'),
(120, 'Kyrgyzstan', 'Bishkek', 'KG', 'KGZ', '417'),
(121, 'Tajikistan', 'Dushanbe', 'TJ', 'TJK', '762'),
(122, 'Turkmenistan', 'Ashgabat', 'TM', 'TKM', '795'),
(123, 'Uzbekistan', 'Tashkent', 'UZ', 'UZB', '860'),
(124, 'China', 'Beijing', 'CN', 'CHN', '156'),
(125, 'Hong Kong', '-', 'HK', 'HKG', '344'),
(126, 'Japan', 'Tokyo', 'JP', 'JPN', '392'),
(127, 'North Korea', 'Pyongyang', 'KP', 'PRK', '408'),
(128, 'South Korea', 'Seoul', 'KR', 'KOR', '410'),
(129, 'Macao', '-', 'MO', 'MAC', '446'),
(130, 'Mongolia', 'Ulaanbaatar', 'MN', 'MNG', '496'),
(131, 'Brunei Darussalam', 'Bandar Seri Begawan', 'BN', 'BRN', '096'),
(132, 'Cambodia', 'Phnom Penh', 'KH', 'KHM', '116'),
(133, 'Indonesia', 'Jakarta', 'ID', 'IDN', '360'),
(134, 'Lao People\'s Democratic Republic', 'Vientiane', 'LA', 'LAO', '418'),
(135, 'Malaysia', 'Kuala Lumpur, Putrajaya', 'MY', 'MYS', '458'),
(136, 'Myanmar', 'Naypyidaw', 'MM', 'MMR', '104'),
(137, 'Philippines', 'Manila', 'PH', 'PHL', '608'),
(138, 'Singapore', 'Singapore', 'SG', 'SGP', '702'),
(139, 'Thailand', 'Bangkok', 'TH', 'THA', '764'),
(140, 'Timor-Leste', 'Dili', 'TL', 'TLS', '626'),
(141, 'Viet Nam', 'Hanoi', 'VN', 'VNM', '704'),
(142, 'Afghanistan', 'Kabul', 'AF', 'AFG', '004'),
(143, 'Bangladesh', 'Dhaka', 'BD', 'BGD', '050'),
(144, 'Bhutan', 'Thimphu', 'BT', 'BTN', '064'),
(145, 'India', 'New Delhi', 'IN', 'IND', '356'),
(146, 'Iran', 'Tehran', 'IR', 'IRN', '364'),
(147, 'Maldives', 'Malé', 'MV', 'MDV', '462'),
(148, 'Nepal', 'Kathmandu', 'NP', 'NPL', '524'),
(149, 'Pakistan', 'Islamabad', 'PK', 'PAK', '586'),
(150, 'Sri Lanka', 'Sri Jayawardenepura Kotte', 'LK', 'LKA', '144'),
(151, 'Armenia', 'Yerevan', 'AM', 'ARM', '051'),
(152, 'Azerbaijan', 'Baku', 'AZ', 'AZE', '031'),
(153, 'Bahrain', 'Manama', 'BH', 'BHR', '048'),
(154, 'Cyprus', 'Nicosia', 'CY', 'CYP', '196'),
(155, 'Georgia', 'Tbilisi', 'GE', 'GEO', '268'),
(156, 'Iraq', 'Baghdad', 'IQ', 'IRQ', '368'),
(157, 'Israel', 'Jerusalem', 'IL', 'ISR', '376'),
(158, 'Jordan', 'Amman', 'JO', 'JOR', '400'),
(159, 'Kuwait', 'Kuwait City', 'KW', 'KWT', '414'),
(160, 'Lebanon', 'Beirut', 'LB', 'LBN', '422'),
(161, 'Oman', 'Muscat', 'OM', 'OMN', '512'),
(162, 'Palestine', 'Jerusalem', 'PS', 'PSE', '275'),
(163, 'Qatar', 'Doha', 'QA', 'QAT', '634'),
(164, 'Saudi Arabia', 'Riyadh', 'SA', 'SAU', '682'),
(165, 'Syrian Arab Republic', 'Damascus', 'SY', 'SYR', '760'),
(166, 'Turkey', 'Ankara', 'TR', 'TUR', '792'),
(167, 'United Arab Emirates', 'Abu Dhabi', 'AE', 'ARE', '784'),
(168, 'Yemen', 'Sana\'a', 'YE', 'YEM', '887'),
(169, 'Belarus', 'Minsk', 'BY', 'BLR', '112'),
(170, 'Bulgaria', 'Sofia', 'BG', 'BGR', '100'),
(171, 'Czechia', 'Prague', 'CZ', 'CZE', '203'),
(172, 'Hungary', 'Budapest', 'HU', 'HUN', '348'),
(173, 'Moldova', 'Chișinău', 'MD', 'MDA', '498'),
(174, 'Poland', 'Warsaw', 'PL', 'POL', '616'),
(175, 'Romania', 'Bucharest', 'RO', 'ROU', '642'),
(176, 'Russian Federation', 'Moscow', 'RU', 'RUS', '643'),
(177, 'Slovakia', 'Bratislava', 'SK', 'SVK', '703'),
(178, 'Ukraine', 'Kiev', 'UA', 'UKR', '804'),
(179, 'Åland Islands', 'Mariehamn', 'AX', 'ALA', '248'),
(180, 'Guernsey', 'St. Peter Port', 'GG', 'GGY', '831'),
(181, 'Jersey', 'St. Helier', 'JE', 'JEY', '832'),
(182, 'Sark', '-', '-', '-', '680'),
(183, 'Denmark', 'Copenhagen', 'DK', 'DNK', '208'),
(184, 'Estonia', 'Tallinn', 'EE', 'EST', '233'),
(185, 'Faroe Islands', 'Tórshavn', 'FO', 'FRO', '234'),
(186, 'Finland', 'Helsinki', 'FI', 'FIN', '246'),
(187, 'Iceland', 'Reykjavík', 'IS', 'ISL', '352'),
(188, 'Ireland', 'Dublin', 'IE', 'IRL', '372'),
(189, 'Isle of Man', 'Douglas', 'IM', 'IMN', '833'),
(190, 'Latvia', 'Riga', 'LV', 'LVA', '428'),
(191, 'Lithuania', 'Vilnius', 'LT', 'LTU', '440'),
(192, 'Norway', 'Oslo', 'NO', 'NOR', '578'),
(193, 'Svalbard and Jan Mayen', '-', 'SJ', 'SJM', '744'),
(194, 'Sweden', 'Stockholm', 'SE', 'SWE', '752'),
(195, 'United Kingdom', 'London', 'GB', 'GBR', '826'),
(196, 'Albania', 'Tirana', 'AL', 'ALB', '008'),
(197, 'Andorra', 'Andorra la Vella', 'AD', 'AND', '020'),
(198, 'Bosnia and Herzegovina', 'Sarajevo', 'BA', 'BIH', '070'),
(199, 'Croatia', 'Zagreb', 'HR', 'HRV', '191'),
(200, 'Gibraltar', 'Gibraltar', 'GI', 'GIB', '292'),
(201, 'Greece', 'Athens', 'GR', 'GRC', '300'),
(202, 'The Holy See', 'Vatican City', 'VA', 'VAT', '336'),
(203, 'Italy', 'Rome', 'IT', 'ITA', '380'),
(204, 'Malta', 'Valletta', 'MT', 'MLT', '470'),
(205, 'Montenegro', 'Podgorica, Cetinje', 'ME', 'MNE', '499'),
(206, 'North Macedonia', 'Skopje', 'MK', 'MKD', '807'),
(207, 'Portugal', 'Lisbon', 'PT', 'PRT', '620'),
(208, 'San Marino', 'San Marino', 'SM', 'SMR', '674'),
(209, 'Serbia', 'Belgrade', 'RS', 'SRB', '688'),
(210, 'Slovenia', 'Ljubljana', 'SI', 'SVN', '705'),
(211, 'Spain', 'Madrid', 'ES', 'ESP', '724'),
(212, 'Austria', 'Vienna', 'AT', 'AUT', '040'),
(213, 'Belgium', 'Brussels', 'BE', 'BEL', '056'),
(214, 'France', 'Paris', 'FR', 'FRA', '250'),
(215, 'Germany', 'Berlin', 'DE', 'DEU', '276'),
(216, 'Liechtenstein', 'Vaduz', 'LI', 'LIE', '438'),
(217, 'Luxembourg', 'Luxembourg', 'LU', 'LUX', '442'),
(218, 'Monaco', 'Monaco', 'MC', 'MCO', '492'),
(219, 'Netherlands', 'Amsterdam', 'NL', 'NLD', '528'),
(220, 'Switzerland', 'Bern', 'CH', 'CHE', '756'),
(221, 'Australia', 'Canberra', 'AU', 'AUS', '036'),
(222, 'Christmas Island', 'Flying Fish Cove', 'CX', 'CXR', '162'),
(223, 'Cocos Islands', 'West Island', 'CC', 'CCK', '166'),
(224, 'Heard Island and McDonald Islands', '-', 'HM', 'HMD', '334'),
(225, 'New Zealand', 'Wellington', 'NZ', 'NZL', '554'),
(226, 'Norfolk Island', 'Kingston', 'NF', 'NFK', '574'),
(227, 'Fiji', 'Suva', 'FJ', 'FJI', '242'),
(228, 'New Caledonia', 'Nouméa', 'NC', 'NCL', '540'),
(229, 'Papua New Guinea', 'Port Moresby', 'PG', 'PNG', '598'),
(230, 'Solomon Islands', 'Honiara', 'SB', 'SLB', '090'),
(231, 'Vanuatu', 'Port Vila', 'VU', 'VUT', '548'),
(232, 'Guam', 'Hagåtña', 'GU', 'GUM', '316'),
(233, 'Kiribati', 'South Tarawa', 'KI', 'KIR', '296'),
(234, 'Marshall Islands', 'Majuro', 'MH', 'MHL', '584'),
(235, 'Micronesia', 'Palikir', 'FM', 'FSM', '583'),
(236, 'Nauru', 'Yaren', 'NR', 'NRU', '520'),
(237, 'Northern Mariana Islands', 'Saipan', 'MP', 'MNP', '580'),
(238, 'Palau', 'Ngerulmud', 'PW', 'PLW', '585'),
(239, 'United States Minor Outlying Islands', 'Washington, D.C.', 'UM', 'UMI', '581'),
(240, 'American Samoa', 'Pago Pago', 'AS', 'ASM', '016'),
(241, 'Cook Islands', 'Avarua', 'CK', 'COK', '184'),
(242, 'French Polynesia', 'Pape\'ete', 'PF', 'PYF', '258'),
(243, 'Niue', 'Alofi', 'NU', 'NIU', '570'),
(244, 'Pitcairn', 'Adamstown', 'PN', 'PCN', '612'),
(245, 'Samoa', 'Apia', 'WS', 'WSM', '882'),
(246, 'Tokelau', 'Fakaofo', 'TK', 'TKL', '772'),
(247, 'Tonga', 'Nukuʻalofa', 'TO', 'TON', '776'),
(248, 'Tuvalu', 'Funafuti', 'TV', 'TUV', '798'),
(249, 'Wallis and Futuna', 'Mata-Utu', 'WF', 'WLF', '876');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `countries_all`
--
ALTER TABLE `countries_all`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `countries_all`
--
ALTER TABLE `countries_all`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=250;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
